### ISSUE TITLE
bot crash

### ISSUE THREAD

**Issue by henosch** [arman29kz/swgoh-bugs-bm-fleet-po-monitor#2]
/client/websocket/WebSocketConnection.js:336:35)                at WebSocketConnection.onMessage (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)               at WebSocket.onMessage (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/ws/lib/event-target.js:120:16)
(node:931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
id: 1)
(node:931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:174                                                     throw er; // Unhandled 'error' event
oh-bugs-bm-fleet-po-monitor/bot.js:71:39)
    at Client.client.on (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/bot.js:31:3)
    at Client.emit (events.js:203:15)                           at WebSocketConnection.triggerReady (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)            at WebSocketConnection.checkIfReady (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)            at GuildCreateHandler.handle (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)    at WebSocketConnection.onPacket (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)                at WebSocketConnection.onMessage (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)               at WebSocket.onMessage (/home/bot/swgoh_tracker/swgoh-bugs-bm-fleet-po-monitor/node_modules/ws/lib/event-target.js:120:16)                                                     (node:1816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                     (node:1816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                                     events.js:174                                                     throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND undefined undefined:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)                                                       Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:401:9)       at Socket.emit (events.js:198:13)                           at emitErrorNT (internal/streams/destroy.js:91:8)           at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by arman29kz** [comment]
Hello, where have you installed it?

**Comment by henosch** [comment]
PI 4 with debian

**Comment by arman29kz** [comment]
Hello, I have launched it through heroku.com:
1. Stack: heroku-20;
2. Framework: Node.js

Config Vars:
1. **appDomain** - yourdomainsmth;
2. **botToken** - discord bot should be created;
3. **writeChannelId** - discord channel id for sending messages

I don't have my own server, so I have used heroku.com with free hours

**Comment by henosch** [comment]
How can I used it on my own server? Node are already installed

**Comment by arman29kz** [comment]
Do you have discord? Pls drop me a message there. Can't promise anything, but will try to help you

My discord id - BrutalMagicianKZ#0217

**Comment by arman29kz** [comment]
Have you already created bot on this site - https://discord.com/developers/applications?

**Comment by henosch** [comment]
Yes,  i have do that your discord ID is wrong

**Comment by arman29kz** [comment]
> Yes, i have do that your discord ID is wrong

Pls try this one **BrutalMagicianKZ # 0217**. By some occasion github deletes 0 after #
